### PR TITLE
docs: Fix cut-and-paste typo

### PR DESCRIPTION
**Pull request by joakimlinde**
Fix cut-and-paste typo introduced when switching to as_duckplyr_tibble()

### CODE REVIEW

**Comment by joakimlinde** [comment]
I see the smoke test failed. Looks like a git issue. No idea what went wrong.

**Comment by krlmlr** [comment]
Thanks. I'm working on the GitHub workflows now, no need to act.

**Comment by krlmlr** [comment]
Thanks, should be auto-merged.

**Comment by krlmlr** [comment]
Need to do more work on the workflows for the case of external contributors. The PR is fine, I'll be pushing to the branch if that's okay with you. Sorry about the noise.

**Comment by joakimlinde** [comment]
No worries. Thanks.

**Pull request merged**
